name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 for Node.js 20 support

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Updated to v3 for Node.js 20 support

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Updated to v3 for Node.js 20 support
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # Updated to v3 for Node.js 20 support

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            your-dockerhub-username/app:latest
            your-dockerhub-username/app:latest-${{ matrix.architecture }}

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
